"""
Residual Validation for CA-EDT-AHMA.

Validates residuals.csv generated by residual_calculator.py.

Checks:
1. Required files exist.
2. Row counts match:
   - scaled_features.csv
   - context_clusters.csv
   - ensemble_predictions.csv
   - residuals.csv
3. Required columns exist.
4. Row alignment is correct using unit_id, cycle, split.
5. Actual X_s values stored in residuals.csv match scaled_features.csv.
6. Ensemble prediction values stored in residuals.csv match ensemble_predictions.csv.
7. residual_Xs_* = actual_Xs_* - ensemble_predicted_Xs_*.
8. abs_residual_Xs_* = abs(residual_Xs_*).
9. Residual temporal features exist and are finite.
10. Optional exact temporal feature validation:
    - rolling mean
    - rolling std
    - trend
    - absolute residual rolling mean

Memory-safe:
- Reads all CSV files in chunks.
- Does not load full residuals.csv into RAM.
- Writes validation metrics safely.

Outputs:
- metrics/residual_validation_metrics.csv
- reports/residual_validation_summary.json
"""

from __future__ import annotations

from pathlib import Path
from time import perf_counter
from typing import Dict, List, Tuple
import gc
import json
import os
import sys

import numpy as np
import pandas as pd


# ======================================================================================
# Standalone script support
# ======================================================================================

if __package__ in {None, ""}:
    BACKEND_ROOT = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..", "..")
    )

    if BACKEND_ROOT not in sys.path:
        sys.path.append(BACKEND_ROOT)


from app.config.Anomaly_Health_Monitering.Config import Config
from app.utils.Anomaly_Health_Monitering.file_utils import (
    atomic_write_csv,
    atomic_write_json,
)
from app.utils.Anomaly_Health_Monitering.logging_utils import get_logger
from app.utils.Anomaly_Health_Monitering.model_utils import get_raw_xs_columns


logger = get_logger(__name__)


class ResidualValidator:
    """
    Memory-safe validator for residuals.csv.
    """

    def __init__(
        self,
        chunk_size: int = 25_000,
        tolerance: float = 1e-5,
        validate_temporal_exact: bool = True,
    ) -> None:
        """
        Initialize residual validator.

        Args:
            chunk_size: Number of rows per validation chunk.
            tolerance: Numerical tolerance for float comparisons.
            validate_temporal_exact: Whether to exactly recompute residual temporal features.
        """
        Config.create_directories()

        self.chunk_size = int(
            getattr(Config, "RESIDUAL_VALIDATION_CHUNK_SIZE", chunk_size)
        )

        self.tolerance = float(
            getattr(Config, "RESIDUAL_VALIDATION_TOLERANCE", tolerance)
        )

        self.validate_temporal_exact = bool(
            getattr(
                Config,
                "RESIDUAL_VALIDATE_TEMPORAL_EXACT",
                validate_temporal_exact,
            )
        )

        self.rolling_window = int(getattr(Config, "ROLLING_WINDOW", 5))

        self.metrics_csv: Path = getattr(
            Config,
            "RESIDUAL_VALIDATION_METRICS_CSV",
            Config.METRIC_DIR / "residual_validation_metrics.csv",
        )

        self.summary_json: Path = getattr(
            Config,
            "RESIDUAL_VALIDATION_SUMMARY_JSON",
            Config.REPORT_DIR / "residual_validation_summary.json",
        )

        if self.chunk_size <= 0:
            raise ValueError("RESIDUAL_VALIDATION_CHUNK_SIZE must be positive.")

        if self.tolerance <= 0:
            raise ValueError("RESIDUAL_VALIDATION_TOLERANCE must be positive.")

        if self.rolling_window <= 1:
            raise ValueError("ROLLING_WINDOW must be greater than 1.")

        print("[PROGRESS] ResidualValidator initialized")
        print(f"[PROGRESS] Chunk size: {self.chunk_size}")
        print(f"[PROGRESS] Tolerance: {self.tolerance}")
        print(f"[PROGRESS] Rolling window: {self.rolling_window}")
        print(f"[PROGRESS] Exact temporal validation: {self.validate_temporal_exact}")
        print(f"[PROGRESS] Metrics CSV: {self.metrics_csv}")
        print(f"[PROGRESS] Summary JSON: {self.summary_json}")

    # ==================================================================================
    # Basic helpers
    # ==================================================================================

    def _count_csv_rows(self, path: Path) -> int:
        """
        Count data rows in a CSV without loading it.

        Args:
            path: CSV path.

        Returns:
            Row count excluding header.
        """
        print(f"[PROGRESS] Counting rows: {path}")

        if not path.exists():
            raise FileNotFoundError(f"File not found: {path}")

        with path.open("r", encoding="utf-8") as file:
            row_count = sum(1 for _ in file) - 1

        row_count = max(row_count, 0)

        print(f"[PROGRESS] Row count for {path.name}: {row_count}")
        return int(row_count)

    def _read_header_df(self, path: Path) -> pd.DataFrame:
        """
        Read CSV header as empty DataFrame.
        """
        print(f"[PROGRESS] Reading header DataFrame: {path}")
        return pd.read_csv(path, nrows=0)

    def _read_header_columns(self, path: Path) -> List[str]:
        """
        Read CSV header columns.
        """
        print(f"[PROGRESS] Reading header columns: {path}")
        return list(pd.read_csv(path, nrows=0).columns)

    def _validate_columns(
        self,
        available_columns: List[str],
        required_columns: List[str],
        label: str,
    ) -> None:
        """
        Validate required columns exist.
        """
        missing = [column for column in required_columns if column not in available_columns]

        if missing:
            print(f"[ERROR] Missing columns for {label}: {missing}")
            raise KeyError(f"Missing columns for {label}: {missing}")

        print(f"[PROGRESS] Required columns validated for {label}")

    def _verify_key_alignment(
        self,
        base_chunk: pd.DataFrame,
        other_chunk: pd.DataFrame,
        merge_columns: List[str],
        label: str,
    ) -> None:
        """
        Verify chunk row alignment.
        """
        if len(base_chunk) != len(other_chunk):
            raise ValueError(
                f"Row count mismatch for {label}: "
                f"base={len(base_chunk)}, other={len(other_chunk)}"
            )

        base_keys = base_chunk[merge_columns].reset_index(drop=True)
        other_keys = other_chunk[merge_columns].reset_index(drop=True)

        if not base_keys.equals(other_keys):
            raise ValueError(
                f"Row-key alignment failed for {label}. "
                "Regenerate outputs using the same base row order."
            )

    def _max_abs_diff(self, a: np.ndarray, b: np.ndarray) -> float:
        """
        Calculate max absolute difference safely.
        """
        if len(a) == 0:
            return 0.0

        return float(np.max(np.abs(a.astype(np.float64) - b.astype(np.float64))))

    # ==================================================================================
    # Required column construction
    # ==================================================================================

    def _build_required_columns(
        self,
        raw_xs_columns: List[str],
    ) -> Dict[str, List[str]]:
        """
        Build all required columns for validation.
        """
        merge_columns = ["unit_id", "cycle", "split"]
        context_columns = [
            "kmeans_context_id",
            "gmm_context_id",
            "context_confidence",
        ]

        ensemble_prediction_columns = [
            f"ensemble_predicted_{sensor}" for sensor in raw_xs_columns
        ]

        residual_columns = [
            f"residual_{sensor}" for sensor in raw_xs_columns
        ]

        abs_residual_columns = [
            f"abs_residual_{sensor}" for sensor in raw_xs_columns
        ]

        resfeat_columns: List[str] = []

        for sensor in raw_xs_columns:
            residual_col = f"residual_{sensor}"
            abs_residual_col = f"abs_residual_{sensor}"

            resfeat_columns.extend(
                [
                    f"resfeat_{residual_col}_rolling_mean_{self.rolling_window}",
                    f"resfeat_{residual_col}_rolling_std_{self.rolling_window}",
                    f"resfeat_{residual_col}_trend",
                    f"resfeat_{abs_residual_col}_rolling_mean_{self.rolling_window}",
                ]
            )

        return {
            "merge": merge_columns,
            "context": context_columns,
            "ensemble_predictions": ensemble_prediction_columns,
            "residuals": residual_columns,
            "abs_residuals": abs_residual_columns,
            "resfeat": resfeat_columns,
            "scaled_required": merge_columns + raw_xs_columns,
            "context_required": merge_columns + context_columns,
            "ensemble_required": merge_columns + ensemble_prediction_columns,
            "residual_required": (
                merge_columns
                + context_columns
                + raw_xs_columns
                + ensemble_prediction_columns
                + residual_columns
                + abs_residual_columns
                + resfeat_columns
            ),
        }

    # ==================================================================================
    # Temporal exact validation
    # ==================================================================================

    def _validate_temporal_features_for_chunk(
        self,
        residual_chunk: pd.DataFrame,
        raw_xs_columns: List[str],
        state: Dict[Tuple[object, object], Dict[str, Dict[str, object]]],
    ) -> Dict[str, float]:
        """
        Recompute temporal residual features chunk-by-chunk and compare.

        Args:
            residual_chunk: Chunk from residuals.csv.
            raw_xs_columns: Raw X_s sensor columns.
            state: Carry-over rolling state.

        Returns:
            Dictionary of max temporal feature differences by feature type.
        """
        max_diffs = {
            "rolling_mean": 0.0,
            "rolling_std": 0.0,
            "trend": 0.0,
            "abs_rolling_mean": 0.0,
        }

        group_columns = ["split", "unit_id"]

        for group_key, group_index in residual_chunk.groupby(
            group_columns,
            sort=False,
        ).groups.items():
            if group_key not in state:
                state[group_key] = {}

            for sensor in raw_xs_columns:
                residual_col = f"residual_{sensor}"
                abs_residual_col = f"abs_residual_{sensor}"

                rolling_mean_col = (
                    f"resfeat_{residual_col}_rolling_mean_{self.rolling_window}"
                )
                rolling_std_col = (
                    f"resfeat_{residual_col}_rolling_std_{self.rolling_window}"
                )
                trend_col = f"resfeat_{residual_col}_trend"
                abs_rolling_mean_col = (
                    f"resfeat_{abs_residual_col}_rolling_mean_{self.rolling_window}"
                )

                sensor_state = state[group_key].get(
                    sensor,
                    {
                        "residual_window": [],
                        "abs_window": [],
                        "last_residual": None,
                    },
                )

                current_residuals = residual_chunk.loc[
                    group_index,
                    residual_col,
                ].to_numpy(dtype=np.float32, copy=False)

                current_abs_residuals = residual_chunk.loc[
                    group_index,
                    abs_residual_col,
                ].to_numpy(dtype=np.float32, copy=False)

                previous_residual_window = np.asarray(
                    sensor_state["residual_window"],
                    dtype=np.float32,
                )
                previous_abs_window = np.asarray(
                    sensor_state["abs_window"],
                    dtype=np.float32,
                )

                combined_residuals = np.concatenate(
                    [previous_residual_window, current_residuals]
                )

                combined_abs_residuals = np.concatenate(
                    [previous_abs_window, current_abs_residuals]
                )

                expected_rolling_mean = (
                    pd.Series(combined_residuals)
                    .rolling(window=self.rolling_window, min_periods=1)
                    .mean()
                    .to_numpy(dtype=np.float32)
                )[-len(current_residuals):]

                expected_rolling_std = (
                    pd.Series(combined_residuals)
                    .rolling(window=self.rolling_window, min_periods=1)
                    .std()
                    .fillna(0.0)
                    .to_numpy(dtype=np.float32)
                )[-len(current_residuals):]

                expected_abs_rolling_mean = (
                    pd.Series(combined_abs_residuals)
                    .rolling(window=self.rolling_window, min_periods=1)
                    .mean()
                    .to_numpy(dtype=np.float32)
                )[-len(current_abs_residuals):]

                expected_trend = np.zeros(len(current_residuals), dtype=np.float32)

                if len(current_residuals) > 0:
                    last_residual = sensor_state["last_residual"]

                    if last_residual is None:
                        expected_trend[0] = 0.0
                    else:
                        expected_trend[0] = current_residuals[0] - float(last_residual)

                    if len(current_residuals) > 1:
                        expected_trend[1:] = np.diff(current_residuals)

                observed_rolling_mean = residual_chunk.loc[
                    group_index,
                    rolling_mean_col,
                ].to_numpy(dtype=np.float32, copy=False)

                observed_rolling_std = residual_chunk.loc[
                    group_index,
                    rolling_std_col,
                ].to_numpy(dtype=np.float32, copy=False)

                observed_trend = residual_chunk.loc[
                    group_index,
                    trend_col,
                ].to_numpy(dtype=np.float32, copy=False)

                observed_abs_rolling_mean = residual_chunk.loc[
                    group_index,
                    abs_rolling_mean_col,
                ].to_numpy(dtype=np.float32, copy=False)

                max_diffs["rolling_mean"] = max(
                    max_diffs["rolling_mean"],
                    self._max_abs_diff(expected_rolling_mean, observed_rolling_mean),
                )
                max_diffs["rolling_std"] = max(
                    max_diffs["rolling_std"],
                    self._max_abs_diff(expected_rolling_std, observed_rolling_std),
                )
                max_diffs["trend"] = max(
                    max_diffs["trend"],
                    self._max_abs_diff(expected_trend, observed_trend),
                )
                max_diffs["abs_rolling_mean"] = max(
                    max_diffs["abs_rolling_mean"],
                    self._max_abs_diff(
                        expected_abs_rolling_mean,
                        observed_abs_rolling_mean,
                    ),
                )

                keep_count = max(self.rolling_window - 1, 1)

                state[group_key][sensor] = {
                    "residual_window": combined_residuals[-keep_count:].tolist(),
                    "abs_window": combined_abs_residuals[-keep_count:].tolist(),
                    "last_residual": float(current_residuals[-1])
                    if len(current_residuals) > 0
                    else sensor_state["last_residual"],
                }

        return max_diffs

    # ==================================================================================
    # Main validation
    # ==================================================================================

    def validate(self) -> Tuple[pd.DataFrame, Dict[str, object]]:
        """
        Run residual validation.

        Returns:
            Tuple of validation metrics DataFrame and summary dictionary.
        """
        print("[PROGRESS] Entering ResidualValidator.validate")

        started = perf_counter()

        files = {
            "scaled": Config.SCALED_CSV,
            "context": Config.CONTEXT_CSV,
            "ensemble": Config.ENSEMBLE_PREDICTIONS_CSV,
            "residuals": Config.RESIDUALS_CSV,
        }

        for label, path in files.items():
            print(f"[PROGRESS] Checking file exists: {label} -> {path}")

            if not path.exists():
                raise FileNotFoundError(f"Required file missing: {label} -> {path}")

        row_counts = {
            label: self._count_csv_rows(path)
            for label, path in files.items()
        }

        if len(set(row_counts.values())) != 1:
            raise ValueError(f"Input/output row counts do not match: {row_counts}")

        expected_rows = row_counts["scaled"]

        if expected_rows <= 0:
            raise ValueError("Residual validation cannot run on zero rows.")

        scaled_header_df = self._read_header_df(Config.SCALED_CSV)
        raw_xs_columns = get_raw_xs_columns(scaled_header_df)

        if not raw_xs_columns:
            raise ValueError("No raw X_s columns found in scaled_features.csv.")

        required = self._build_required_columns(raw_xs_columns)

        scaled_columns = self._read_header_columns(Config.SCALED_CSV)
        context_columns = self._read_header_columns(Config.CONTEXT_CSV)
        ensemble_columns = self._read_header_columns(Config.ENSEMBLE_PREDICTIONS_CSV)
        residual_columns = self._read_header_columns(Config.RESIDUALS_CSV)

        self._validate_columns(
            scaled_columns,
            required["scaled_required"],
            "scaled_features.csv",
        )
        self._validate_columns(
            context_columns,
            required["context_required"],
            "context_clusters.csv",
        )
        self._validate_columns(
            ensemble_columns,
            required["ensemble_required"],
            "ensemble_predictions.csv",
        )
        self._validate_columns(
            residual_columns,
            required["residual_required"],
            "residuals.csv",
        )

        merge_columns = required["merge"]

        scaled_usecols = required["scaled_required"]
        context_usecols = required["context_required"]
        ensemble_usecols = required["ensemble_required"]
        residual_usecols = required["residual_required"]

        scaled_iter = pd.read_csv(
            Config.SCALED_CSV,
            usecols=scaled_usecols,
            chunksize=self.chunk_size,
            low_memory=True,
        )

        context_iter = pd.read_csv(
            Config.CONTEXT_CSV,
            usecols=context_usecols,
            chunksize=self.chunk_size,
            low_memory=True,
        )

        ensemble_iter = pd.read_csv(
            Config.ENSEMBLE_PREDICTIONS_CSV,
            usecols=ensemble_usecols,
            chunksize=self.chunk_size,
            low_memory=True,
        )

        residual_iter = pd.read_csv(
            Config.RESIDUALS_CSV,
            usecols=residual_usecols,
            chunksize=self.chunk_size,
            low_memory=True,
        )

        max_actual_copy_diff = 0.0
        max_prediction_copy_diff = 0.0
        max_residual_formula_diff = 0.0
        max_abs_residual_formula_diff = 0.0
        max_context_confidence_diff = 0.0

        max_temporal_diffs = {
            "rolling_mean": 0.0,
            "rolling_std": 0.0,
            "trend": 0.0,
            "abs_rolling_mean": 0.0,
        }

        non_finite_count = 0
        total_rows_seen = 0
        chunk_index = 0

        residual_abs_sum_by_split: Dict[str, float] = {
            Config.DEV_SPLIT_NAME: 0.0,
            Config.TEST_SPLIT_NAME: 0.0,
        }
        residual_sq_sum_by_split: Dict[str, float] = {
            Config.DEV_SPLIT_NAME: 0.0,
            Config.TEST_SPLIT_NAME: 0.0,
        }
        residual_value_count_by_split: Dict[str, int] = {
            Config.DEV_SPLIT_NAME: 0,
            Config.TEST_SPLIT_NAME: 0,
        }

        temporal_state: Dict[
            Tuple[object, object],
            Dict[str, Dict[str, object]],
        ] = {}

        print("[PROGRESS] Starting memory-safe residual validation")

        for scaled_chunk, context_chunk, ensemble_chunk, residual_chunk in zip(
            scaled_iter,
            context_iter,
            ensemble_iter,
            residual_iter,
        ):
            chunk_index += 1
            total_rows_seen += len(scaled_chunk)

            print("=" * 100)
            print(f"[PROGRESS] Validating residual chunk #{chunk_index}")
            print(f"[PROGRESS] Chunk rows: {len(scaled_chunk)}")
            print(f"[PROGRESS] Total rows seen: {total_rows_seen}")

            self._verify_key_alignment(
                base_chunk=scaled_chunk,
                other_chunk=context_chunk,
                merge_columns=merge_columns,
                label="context CSV",
            )
            self._verify_key_alignment(
                base_chunk=scaled_chunk,
                other_chunk=ensemble_chunk,
                merge_columns=merge_columns,
                label="ensemble predictions CSV",
            )
            self._verify_key_alignment(
                base_chunk=scaled_chunk,
                other_chunk=residual_chunk,
                merge_columns=merge_columns,
                label="residuals CSV",
            )

            for context_column in required["context"]:
                source_values = context_chunk[context_column].to_numpy()
                residual_values = residual_chunk[context_column].to_numpy()

                if context_column == "context_confidence":
                    max_context_confidence_diff = max(
                        max_context_confidence_diff,
                        self._max_abs_diff(source_values, residual_values),
                    )
                else:
                    if not np.array_equal(source_values, residual_values):
                        raise ValueError(
                            f"Context ID mismatch detected for column: {context_column}"
                        )

            numeric_check_columns = (
                raw_xs_columns
                + required["ensemble_predictions"]
                + required["residuals"]
                + required["abs_residuals"]
                + required["resfeat"]
            )

            non_finite_count += int(
                residual_chunk[numeric_check_columns]
                .replace([np.inf, -np.inf], np.nan)
                .isna()
                .sum()
                .sum()
            )

            for sensor in raw_xs_columns:
                pred_col = f"ensemble_predicted_{sensor}"
                residual_col = f"residual_{sensor}"
                abs_residual_col = f"abs_residual_{sensor}"

                actual_source = scaled_chunk[sensor].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )
                actual_saved = residual_chunk[sensor].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )

                pred_source = ensemble_chunk[pred_col].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )
                pred_saved = residual_chunk[pred_col].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )

                residual_saved = residual_chunk[residual_col].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )
                abs_residual_saved = residual_chunk[abs_residual_col].to_numpy(
                    dtype=np.float32,
                    copy=False,
                )

                expected_residual = actual_source - pred_source
                expected_abs_residual = np.abs(expected_residual)

                max_actual_copy_diff = max(
                    max_actual_copy_diff,
                    self._max_abs_diff(actual_source, actual_saved),
                )
                max_prediction_copy_diff = max(
                    max_prediction_copy_diff,
                    self._max_abs_diff(pred_source, pred_saved),
                )
                max_residual_formula_diff = max(
                    max_residual_formula_diff,
                    self._max_abs_diff(expected_residual, residual_saved),
                )
                max_abs_residual_formula_diff = max(
                    max_abs_residual_formula_diff,
                    self._max_abs_diff(expected_abs_residual, abs_residual_saved),
                )

                for split in [Config.DEV_SPLIT_NAME, Config.TEST_SPLIT_NAME]:
                    split_mask = residual_chunk["split"] == split

                    if not split_mask.any():
                        continue

                    split_residuals = residual_chunk.loc[
                        split_mask,
                        residual_col,
                    ].to_numpy(dtype=np.float32, copy=False)

                    residual_abs_sum_by_split[split] += float(
                        np.abs(split_residuals).sum(dtype=np.float64)
                    )
                    residual_sq_sum_by_split[split] += float(
                        np.square(split_residuals, dtype=np.float64).sum()
                    )
                    residual_value_count_by_split[split] += int(len(split_residuals))

            if self.validate_temporal_exact:
                chunk_temporal_diffs = self._validate_temporal_features_for_chunk(
                    residual_chunk=residual_chunk,
                    raw_xs_columns=raw_xs_columns,
                    state=temporal_state,
                )

                for key, value in chunk_temporal_diffs.items():
                    max_temporal_diffs[key] = max(max_temporal_diffs[key], value)

            del scaled_chunk
            del context_chunk
            del ensemble_chunk
            del residual_chunk
            gc.collect()

        if total_rows_seen != expected_rows:
            raise ValueError(
                "Residual validation row scan mismatch. "
                f"seen={total_rows_seen}, expected={expected_rows}"
            )

        validation_records: List[Dict[str, object]] = []

        def add_check(
            check_name: str,
            max_error: float,
            tolerance: float,
            details: str,
        ) -> None:
            passed = bool(max_error <= tolerance)

            validation_records.append(
                {
                    "check_name": check_name,
                    "status": "PASSED" if passed else "FAILED",
                    "max_error": float(max_error),
                    "tolerance": float(tolerance),
                    "details": details,
                }
            )

        add_check(
            "actual_xs_copy",
            max_actual_copy_diff,
            self.tolerance,
            "Residual CSV actual X_s columns match scaled_features.csv.",
        )
        add_check(
            "ensemble_prediction_copy",
            max_prediction_copy_diff,
            self.tolerance,
            "Residual CSV ensemble prediction columns match ensemble_predictions.csv.",
        )
        add_check(
            "residual_formula",
            max_residual_formula_diff,
            self.tolerance,
            "residual_Xs_* equals actual_Xs_* - ensemble_predicted_Xs_*.",
        )
        add_check(
            "abs_residual_formula",
            max_abs_residual_formula_diff,
            self.tolerance,
            "abs_residual_Xs_* equals abs(residual_Xs_*).",
        )
        add_check(
            "context_confidence_copy",
            max_context_confidence_diff,
            self.tolerance,
            "context_confidence copied correctly from context_clusters.csv.",
        )

        finite_status = "PASSED" if non_finite_count == 0 else "FAILED"

        validation_records.append(
            {
                "check_name": "finite_numeric_values",
                "status": finite_status,
                "max_error": float(non_finite_count),
                "tolerance": 0.0,
                "details": "Numeric residual/resfeat columns contain no NaN or infinite values.",
            }
        )

        if self.validate_temporal_exact:
            add_check(
                "resfeat_rolling_mean",
                max_temporal_diffs["rolling_mean"],
                self.tolerance,
                "Residual rolling mean temporal features are correct.",
            )
            add_check(
                "resfeat_rolling_std",
                max_temporal_diffs["rolling_std"],
                self.tolerance,
                "Residual rolling std temporal features are correct.",
            )
            add_check(
                "resfeat_trend",
                max_temporal_diffs["trend"],
                self.tolerance,
                "Residual trend temporal features are correct.",
            )
            add_check(
                "resfeat_abs_rolling_mean",
                max_temporal_diffs["abs_rolling_mean"],
                self.tolerance,
                "Absolute residual rolling mean temporal features are correct.",
            )

        for split in [Config.DEV_SPLIT_NAME, Config.TEST_SPLIT_NAME]:
            count = residual_value_count_by_split[split]

            if count <= 0:
                continue

            mae_like = residual_abs_sum_by_split[split] / count
            rmse_like = float(np.sqrt(residual_sq_sum_by_split[split] / count))

            validation_records.append(
                {
                    "check_name": f"{split}_residual_magnitude_summary",
                    "status": "INFO",
                    "max_error": float(rmse_like),
                    "tolerance": 0.0,
                    "details": (
                        f"mean_abs_residual={mae_like:.8f}, "
                        f"rmse_residual={rmse_like:.8f}, "
                        f"values_checked={count}"
                    ),
                }
            )

        metrics_df = pd.DataFrame(validation_records)

        failed_checks = metrics_df[metrics_df["status"] == "FAILED"]
        passed = failed_checks.empty

        duration = perf_counter() - started

        summary = {
            "status": "success" if passed else "failed",
            "message": (
                "Residual validation passed."
                if passed
                else "Residual validation found failed checks."
            ),
            "rows_checked": int(total_rows_seen),
            "raw_xs_sensor_count": int(len(raw_xs_columns)),
            "raw_xs_sensors": raw_xs_columns,
            "chunk_size": int(self.chunk_size),
            "rolling_window": int(self.rolling_window),
            "tolerance": float(self.tolerance),
            "validate_temporal_exact": bool(self.validate_temporal_exact),
            "failed_check_count": int(len(failed_checks)),
            "total_check_count": int(len(metrics_df)),
            "max_actual_copy_diff": float(max_actual_copy_diff),
            "max_prediction_copy_diff": float(max_prediction_copy_diff),
            "max_residual_formula_diff": float(max_residual_formula_diff),
            "max_abs_residual_formula_diff": float(max_abs_residual_formula_diff),
            "max_context_confidence_diff": float(max_context_confidence_diff),
            "non_finite_count": int(non_finite_count),
            "max_temporal_diffs": {
                key: float(value) for key, value in max_temporal_diffs.items()
            },
            "duration_seconds": float(duration),
            "duration_minutes": float(duration / 60.0),
        }

        print("[PROGRESS] Residual validation completed")
        print(f"[PROGRESS] Rows checked: {total_rows_seen}")
        print(f"[PROGRESS] Failed checks: {len(failed_checks)}")
        print(f"[PROGRESS] Duration seconds: {duration:.2f}")
        print(f"[PROGRESS] Duration minutes: {duration / 60.0:.2f}")

        print("[PROGRESS] Residual validation summary:")
        print(json.dumps(summary, indent=2))

        return metrics_df, summary

    def run(self) -> Dict[str, object]:
        """
        Run validation and write metrics/summary outputs.

        Returns:
            Stage response dictionary.
        """
        print("[PROGRESS] Entering ResidualValidator.run")

        try:
            metrics_df, summary = self.validate()

            print(f"[PROGRESS] Writing residual validation metrics to: {self.metrics_csv}")
            atomic_write_csv(metrics_df, self.metrics_csv)

            print(f"[PROGRESS] Writing residual validation summary to: {self.summary_json}")
            atomic_write_json(summary, self.summary_json)

            response = {
                "status": summary["status"],
                "message": summary["message"],
                "metrics_file": str(self.metrics_csv),
                "summary_file": str(self.summary_json),
                "records_count": int(len(metrics_df)),
                "rows_checked": int(summary["rows_checked"]),
                "failed_check_count": int(summary["failed_check_count"]),
            }

            print(f"[PROGRESS] Residual validator response: {response}")
            return response

        except Exception as exc:
            print(f"[ERROR] Residual validation failed: {exc}")
            logger.exception("Residual validation failed.")
            raise RuntimeError("Residual validation failed.") from exc


def run_residual_validation() -> Dict[str, object]:
    """
    Execute residual validation.
    """
    validator = ResidualValidator()
    return validator.run()


if __name__ == "__main__":
    print("[PROGRESS] validate_residuals.py execution started")
    result = run_residual_validation()
    print("[PROGRESS] validate_residuals.py execution finished")
    print(result)